name: Deploy
description: checkout, setup, install deps, prepare, build, and deploy

runs:
  using: composite
  steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn --ignore-scripts
