service: rules-interface

stage: ${env.STAGE}
cloudfrontId: ${env.CLOUDFRONT_ID}
cloudfrontCertificateArn: ${env.CLOUDFRONT_CERTIFICATE_ARN}
cloudfrontAlias: ${env.CLOUDFRONT_ALIAS}

rules-interface:
  component: "@sls-next/serverless-component"
  inputs:
    bucketRegion: eu-west-1
    bucketName: 'rules-interface-${stage}'
    cloudfront:
      distributionId: ${cloudfrontId}
      aliases: ['${cloudfrontAlias}']
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: ${cloudfrontCertificateArn}
