name: Deploy
description: checkout, setup, install deps, prepare, build, and deploy

runs:
  using: composite
  steps:
      - name: Prepare build
        run: yarn prepare
        env:
          REACT_APP_GRAPHQL_URI: ${{ vars.REACT_APP_GRAPHQL_URI }}

      - name: Build
        run: yarn build
        env:
          REACT_APP_GRAPHQL_URI: ${{ vars.REACT_APP_GRAPHQL_URI }}
          REACT_APP_REST_URI: ${{ vars.REACT_APP_REST_URI }}

          PUBLIC_URL: ${{ vars.PUBLIC_URL }}

          REACT_APP_ALGOLIA_ID: ${{ vars.REACT_APP_ALGOLIA_ID }}
          REACT_APP_ALGOLIA_KEY: ${{ vars.REACT_APP_ALGOLIA_KEY }}

          REACT_APP_STRIPE_ID: ${{ vars.REACT_APP_STRIPE_ID }}

          REACT_APP_STARKNET_NETWORK_NAME: ${{ vars.REACT_APP_STARKNET_NETWORK_NAME }}

          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
