name: Deploy dev

on:
  # manual trigger
  workflow_dispatch:

jobs:
  deploy-dev:

    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://dev.rules.art

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy
        uses: ./.github/actions/deploy
