name: Deploy prod

on:
  # manual trigger
  workflow_dispatch:

jobs:
  deploy-prod:

    runs-on: ubuntu-latest

    environment:
      name: prod
      url: https://rules.art

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy
        uses: ./.github/actions/deploy
